version: 2
jobs:
  sync:
    docker:
    - image: devatherock/git-sync:1.0.0
    working_directory: ~/jul-jsonformatter
    environment:
      PLUGIN_TARGET_REPO: "git@bitbucket.org:devaprasadh/jul-jsonformatter.git"  
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
        - "11:4f:6c:a3:16:52:98:03:17:30:39:f8:2a:38:50:bc"
    - run: sh /scripts/entry-point.sh
           
workflows:
  version: 2
  git-sync:
    jobs:
    - sync:
        filters:
          branches:
            only: master