version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/jul-jsonformatter
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: ./gradlew check -x test
      - store_test_results:
          path: test
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/jul-jsonformatter
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: ./gradlew build -x test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs
      - store_artifacts:
          path: build/reports/tests/test
  sync:
    docker:
    - image: devatherock/git-sync:1.0.0
    working_directory: ~/jul-jsonformatter
    environment:
      PLUGIN_TARGET_REPO: "git@bitbucket.org:devaprasadh/jul-jsonformatter.git"  
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
        - "11:4f:6c:a3:16:52:98:03:17:30:39:f8:2a:38:50:bc"
    - run: sh /scripts/entry-point.sh
           
workflows:
  version: 2
  git-sync:
    jobs:
    - sync:
        filters:
          branches:
            only: master
  build-test:
    jobs:
    - test:
        filters:
          branches:
            ignore: 
            - master
    - build:
        filters:
          branches:
            only: master            